import argparse

def parse_args():    
    parser = argparse.ArgumentParser()
    parser.add_argument('-net', type=str, default='sam2', help='net type')
    parser.add_argument('-encoder', type=str, default='vit_b', help='encoder type')
    parser.add_argument('-exp_name', default='samba_train_test', type=str, help='experiment name')
    parser.add_argument('-vis', action="store_true", help='Generate visualisation during validation')
    parser.add_argument('-train_vis', type=bool, default=False, help='Generate visualisation during training')
    parser.add_argument('-prompt', type=str, default='bbox', help='type of prompt, bbox or click')
    parser.add_argument('-prompt_freq', type=int, default=2, help='frequency of giving prompt in 3D images')
    parser.add_argument('-pretrain', type=str, default="", help='path of pretrain weights')
    parser.add_argument('-val_freq',type=int,default=3,help='interval between each validation')
    parser.add_argument('-gpu', type=bool, default=True, help='use gpu or not')
    parser.add_argument('-gpu_device', type=int, default=0, help='use which gpu')
    parser.add_argument('-image_size', type=int, default=1024, help='image_size')
    parser.add_argument('-out_size', type=int, default=1024, help='output_size')
    parser.add_argument('-distributed', action="store_true", help='multi GPU ids to use')
    parser.add_argument('-dataset', default='btcv' ,type=str,help='dataset name')
    parser.add_argument('-sam_ckpt', type=str, default=None, help='sam checkpoint address')
    parser.add_argument('-sam_config', type=str, default="sam2_hiera_t" , help='sam checkpoint address')
    parser.add_argument('-video_length', type=int, default=16, help='sam checkpoint address')
    parser.add_argument('-b', type=int, default=1, help='batch size for dataloader')
    parser.add_argument('-lr', type=float, default=1e-4, help='initial learning rate')
    parser.add_argument('-weights', type=str, default=0, help='the weights file you want to test')
    parser.add_argument('-multimask_output', type=int, default=1 , help='the number of masks output for multi-class segmentation')
    parser.add_argument('-memory_bank_size', type=int, default=16, help='sam 2d memory bank size')
    parser.add_argument('-support_instance', type=str, default="img0039", help='support instance'),
    parser.add_argument('-data_path', type=str, default='/mnt/12T/cuong/AAAI/Combined_Dataset', help='The path of segmentation data'),
    parser.add_argument('-num_support', type=int, default=10, help='saving trained checkpoints')
    parser.add_argument('-save_ckpt', type=bool, default=True, help='enable wandb')
    parser.add_argument('-wandb_enabled', action="store_true", help='enable wandb')
    parser.add_argument('-checkpoint_path', type=str, default="/mnt/12T/cuong/medsam2-icl/checkpoint", help='checkpoint root path')
    parser.add_argument('-truncated_test_frame', type=bool, default=False, help='checkpoint root path')
    parser.add_argument('-task', type=str, default='', help='msd task, leave default for all tasks')
    parser.add_argument('-ep', type=int, default=50, help='number of training epoch')
    parser.add_argument('-lazy_penalty', type=float, default=-1, help='number of training epoch')
    parser.add_argument('-invalid_penalty', type=float, default=-5, help='number of training epoch')
    parser.add_argument('-q_updates_per_step', type=int, default=1, help='number of agent updates per training step')
    parser.add_argument('-rl_config', type=str, default='normal_agent.yaml', help='number of agent updates per training step')
    parser.add_argument('-eval_fg_point', type=int, default=1)
    parser.add_argument('-eval_bg_point', type=int, default=0)
    opt = parser.parse_args()

    return opt
