CUDA_VISIBLE_DEVICES=0 python train_3d.py \
    -exp_name msdTask3+grpo+entropy1e-1+num_support10+clip_grad0.1 \
    -sam_ckpt /mnt/12T/cuong/medsam2-icl-ql/checkpoint/sam2_hiera_tiny.pt \
    -rl_config rl_modules/config/grpo_po_agent.yaml \
    -checkpoint_path ./output/msdTask3+grpo+entropy1e-1+num_support0+clip_grad0.1 \
    -dataset msd \
    -task Task03_Liver \
    -data_path /mnt/12T/cuong/AAAI/Combined_Dataset/MSD \
    -lr 1e-4 \
    -val_freq 1 \
    -ep 300 \
    -q_updates_per_step 2 \
    -lazy_penalty 0 \
    -invalid_penalty 0.0 \
    -num_support 0 \
