agent:
  _target_: sam2_train.rl_modules.policy_optimization.ppo_agent.PPOAgent
  num_maskmem: 6
  policy_lr: 1e-4
  value_lr: 1e-4
  gamma: 0.99
  beta: 0.99
  buffer_size: 1028
  batch_size: 128
  entropy_weight: 0.01
  epsilon: 0.2
  tau: 0.9
  lr_T_max: 50
  min_lr: 5e-5
  n_layers: 2
  target_kl: 0.02
  sam2_dim:
    n_query: 16
    image_dim: 256
    memory_dim: 64
    obj_ptr_dim: 256
    image_summary_dim: 128